config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'

  devise_for :users
  root 'movies#index'
  get '/movies/:id/reviews' => 'reviews#create'
  resources :movies

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, Movie
      else
        can :read, Movie
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  mount_uploader :image_url, ImageUploader
  has_many :reviews

  def avg
    total = 0
    reviews.each do |review|
      total += review.rating
    end
    if reviews.count == 0
      0
    else
      total.to_f/reviews.count
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    if role == "admin"
      true
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  # before_action :check_admin, only: [:edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    # @movies = Movie.all
    @movies = Movie.order(id: :desc).page(params[:page])
    # authorize! :read, Movie
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    # @sum = 0
    # count = 0
    # @movie.reviews.each do |r|
    #   @sum = @sum + r.rating
    #   count += 1
    # end
    # @avg = @sum/count

    # @avg = @movie.reviews.average(:rating)
    # authorize! :read, Movie
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    # authorize! :create, Movie
  end

  # GET /movies/1/edit
  def edit
    # authorize! :update, Movie
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
      # authorize! :create, Movie
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
      # authorize! :update, Movie
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
    # authorize! :destroy, Movie
  end

  private
    # def check_admin
    #   # if current_user.admin?
    #   #   true
    #   # end
    #   unless current_user.admin?
    #     redirect_to root_path
    #   end
    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :desc, :image_url)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    Review.create(
      movie_id: params[:id],
      rating: params[:rating],
      comment: params[:comment]
    )

    redirect_to movie_path(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_login.erb
<%= link_to 'Home', root_path%>
<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %><br/>
  Welcome! <%= current_user.email %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'Sign_up', new_user_registration_path %>
<% end %>

  <!-- <p class="notice"><%#= flash[:notice] %></p> -->
  <!-- <p class="alert"><%#= flash[:alert] %></p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <title>Watcha 영화평점 서비스</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/login' %>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.file_field :image_url %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= image_tag movie.image_url, height: 80, width: 80 %></td>
        <td><%= movie.desc %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @movies %>
<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @movie.desc %>
</p>

<p>
  <strong>image:</strong><br/>
  <%= image_tag @movie.image_url %>
</p>

<%= form_tag("/movies/#{@movie.id}/reviews", method: :get) do %>
<p>
  <strong>Rating:</strong><br/>
  <%= radio_button_tag(:rating, "1")%>
  <%= label_tag(:point_1, "1")%>
  <%= radio_button_tag(:rating, "2")%>
  <%= label_tag(:point_2, "2")%>
  <%= radio_button_tag(:rating, "3")%>
  <%= label_tag(:point_3, "3")%>
  <%= radio_button_tag(:rating, "4")%>
  <%= label_tag(:point_4, "4")%>
  <%= radio_button_tag(:rating, "5")%>
  <%= label_tag(:point_5, "5")%>
</p>
<%= text_field_tag(:comment)%>
<%= submit_tag("Comment")%>
<% end %>

<!-- 리뷰만 다 가져와서 보여주는 곳 -->
<% @movie.reviews.each do |review| %>
  <p>
    <%= review.rating %>
  </p>
  <p>
    <%= review.comment %>
  </p>
<% end %>

<hr/>
<p>
  Average : <%= @movie.avg %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>